all: 2pddl-typed 2pddl-untyped

2pddl-typed: 2pddl-typed.c
	$(CC) 2pddl-typed.c -o 2pddl-typed

2pddl-untyped: 2pddl-untyped.c
	$(CC) 2pddl-untyped.c -o 2pddl-untyped

clean:
	rm -f 2pddl-typed 2pddl-untyped
