
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance-146)
    (:domain obfuscated_randomized_logistics)

    (:objects
        object_0 object_1 object_10 object_11 object_12 object_13 object_14 object_15 object_16 object_17 object_18 object_19 object_2 object_20 object_3 object_4 object_5 object_6 object_7 object_8 object_9 - object
    )

    (:init
        (anav4gem8e8nrk78 object_0)
        (arsbumagdtb748l6 object_3)
        (arsbumagdtb748l6 object_1)
        (arsbumagdtb748l6 object_2)
        (qg9duf682li1kpbe object_5)
        (qg9duf682li1kpbe object_4)
        (qg9duf682li1kpbe object_6)
        (cbaj1n1wo5bq3ezl object_14)
        (cbaj1n1wo5bq3ezl object_9)
        (cbaj1n1wo5bq3ezl object_8)
        (cbaj1n1wo5bq3ezl object_15)
        (cbaj1n1wo5bq3ezl object_13)
        (cbaj1n1wo5bq3ezl object_7)
        (cbaj1n1wo5bq3ezl object_11)
        (cbaj1n1wo5bq3ezl object_10)
        (cbaj1n1wo5bq3ezl object_12)
        (s8mp0xjykmt0fawa object_7 object_1)
        (s8mp0xjykmt0fawa object_11 object_2)
        (s8mp0xjykmt0fawa object_15 object_3)
        (s8mp0xjykmt0fawa object_14 object_3)
        (s8mp0xjykmt0fawa object_9 object_1)
        (s8mp0xjykmt0fawa object_10 object_2)
        (s8mp0xjykmt0fawa object_12 object_2)
        (s8mp0xjykmt0fawa object_8 object_1)
        (s8mp0xjykmt0fawa object_13 object_3)
        (slhkq82juy2qo1pi object_10)
        (slhkq82juy2qo1pi object_13)
        (slhkq82juy2qo1pi object_7)
        (zwcd0caosqrvypn9 object_16)
        (zwcd0caosqrvypn9 object_17)
        (zwcd0caosqrvypn9 object_18)
        (zwcd0caosqrvypn9 object_19)
        (zwcd0caosqrvypn9 object_20)
        (uiat7ywwr0i6j87c object_4 object_9)
        (uiat7ywwr0i6j87c object_17 object_11)
        (uiat7ywwr0i6j87c object_16 object_15)
        (uiat7ywwr0i6j87c object_19 object_15)
        (uiat7ywwr0i6j87c object_6 object_14)
        (uiat7ywwr0i6j87c object_0 object_10)
        (uiat7ywwr0i6j87c object_18 object_8)
        (uiat7ywwr0i6j87c object_20 object_7)
        (uiat7ywwr0i6j87c object_5 object_11)
    )

    (:goal
        (and (uiat7ywwr0i6j87c object_16 object_7) (uiat7ywwr0i6j87c object_17 object_14) (uiat7ywwr0i6j87c object_19 object_10) (uiat7ywwr0i6j87c object_20 object_13) (uiat7ywwr0i6j87c object_18 object_15))
    )

    
    
    
)

