
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance-2)
    (:domain obfuscated_randomized_logistics)

    (:objects
        object_0 object_1 object_2 object_3 object_4 object_5 object_6 object_7 object_8 - object
    )

    (:init
        (anav4gem8e8nrk78 object_0)
        (anav4gem8e8nrk78 object_1)
        (arsbumagdtb748l6 object_3)
        (arsbumagdtb748l6 object_2)
        (qg9duf682li1kpbe object_4)
        (qg9duf682li1kpbe object_5)
        (cbaj1n1wo5bq3ezl object_7)
        (cbaj1n1wo5bq3ezl object_6)
        (s8mp0xjykmt0fawa object_7 object_3)
        (s8mp0xjykmt0fawa object_6 object_2)
        (slhkq82juy2qo1pi object_7)
        (slhkq82juy2qo1pi object_6)
        (zwcd0caosqrvypn9 object_8)
        (uiat7ywwr0i6j87c object_8 object_7)
        (uiat7ywwr0i6j87c object_0 object_7)
        (uiat7ywwr0i6j87c object_5 object_7)
        (uiat7ywwr0i6j87c object_4 object_6)
        (uiat7ywwr0i6j87c object_1 object_7)
    )

    (:goal
        (uiat7ywwr0i6j87c object_8 object_6)
    )

    
    
    
)

