
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance-69)
    (:domain obfuscated_randomized_logistics)

    (:objects
        object_0 object_1 object_10 object_11 object_12 object_13 object_14 object_15 object_2 object_3 object_4 object_5 object_6 object_7 object_8 object_9 - object
    )

    (:init
        (anav4gem8e8nrk78 object_0)
        (arsbumagdtb748l6 object_3)
        (arsbumagdtb748l6 object_1)
        (arsbumagdtb748l6 object_2)
        (qg9duf682li1kpbe object_5)
        (qg9duf682li1kpbe object_4)
        (qg9duf682li1kpbe object_6)
        (cbaj1n1wo5bq3ezl object_9)
        (cbaj1n1wo5bq3ezl object_8)
        (cbaj1n1wo5bq3ezl object_7)
        (cbaj1n1wo5bq3ezl object_11)
        (cbaj1n1wo5bq3ezl object_10)
        (cbaj1n1wo5bq3ezl object_12)
        (s8mp0xjykmt0fawa object_7 object_1)
        (s8mp0xjykmt0fawa object_9 object_2)
        (s8mp0xjykmt0fawa object_11 object_3)
        (s8mp0xjykmt0fawa object_10 object_2)
        (s8mp0xjykmt0fawa object_8 object_1)
        (s8mp0xjykmt0fawa object_12 object_3)
        (slhkq82juy2qo1pi object_11)
        (slhkq82juy2qo1pi object_7)
        (slhkq82juy2qo1pi object_9)
        (zwcd0caosqrvypn9 object_15)
        (zwcd0caosqrvypn9 object_13)
        (zwcd0caosqrvypn9 object_14)
        (uiat7ywwr0i6j87c object_6 object_11)
        (uiat7ywwr0i6j87c object_4 object_7)
        (uiat7ywwr0i6j87c object_13 object_8)
        (uiat7ywwr0i6j87c object_0 object_7)
        (uiat7ywwr0i6j87c object_5 object_9)
        (uiat7ywwr0i6j87c object_15 object_11)
        (uiat7ywwr0i6j87c object_14 object_9)
    )

    (:goal
        (and (uiat7ywwr0i6j87c object_13 object_10) (uiat7ywwr0i6j87c object_15 object_9) (uiat7ywwr0i6j87c object_14 object_9))
    )

    
    
    
)

