
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance-3)
    (:domain obfuscated_deceptive_logistics)

    (:objects
        object_0 object_1 object_2 object_3 object_4 object_5 object_6 object_7 object_8 - object
    )

    (:init
        (cats object_0)
        (stupendous object_2)
        (stupendous object_1)
        (sneeze object_4)
        (sneeze object_3)
        (texture object_6)
        (texture object_5)
        (collect object_5 object_1)
        (collect object_6 object_2)
        (spring object_6)
        (spring object_5)
        (hand object_7)
        (hand object_8)
        (next object_3 object_5)
        (next object_4 object_6)
        (next object_7 object_6)
        (next object_0 object_6)
        (next object_8 object_5)
    )

    (:goal
        (and (next object_8 object_6) (next object_7 object_6))
    )

    
    
    
)

