
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance-58)
    (:domain obfuscated_deceptive_logistics)

    (:objects
        object_0 object_1 object_10 object_11 object_12 object_13 object_14 object_2 object_3 object_4 object_5 object_6 object_7 object_8 object_9 - object
    )

    (:init
        (cats object_2)
        (cats object_0)
        (cats object_1)
        (stupendous object_4)
        (stupendous object_5)
        (stupendous object_3)
        (sneeze object_7)
        (sneeze object_8)
        (sneeze object_6)
        (texture object_11)
        (texture object_9)
        (texture object_10)
        (collect object_11 object_5)
        (collect object_10 object_4)
        (collect object_9 object_3)
        (spring object_11)
        (spring object_9)
        (spring object_10)
        (hand object_14)
        (hand object_13)
        (hand object_12)
        (next object_2 object_11)
        (next object_13 object_10)
        (next object_8 object_11)
        (next object_6 object_9)
        (next object_7 object_10)
        (next object_12 object_10)
        (next object_14 object_11)
        (next object_1 object_11)
        (next object_0 object_10)
    )

    (:goal
        (and (next object_13 object_9) (next object_12 object_9) (next object_14 object_9))
    )

    
    
    
)

