
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance-265)
    (:domain obfuscated_deceptive_logistics)

    (:objects
        object_0 object_1 object_10 object_11 object_12 object_13 object_14 object_15 object_16 object_17 object_18 object_19 object_2 object_20 object_21 object_22 object_23 object_3 object_4 object_5 object_6 object_7 object_8 object_9 - object
    )

    (:init
        (cats object_0)
        (cats object_1)
        (stupendous object_2)
        (stupendous object_4)
        (stupendous object_3)
        (sneeze object_7)
        (sneeze object_6)
        (sneeze object_5)
        (texture object_9)
        (texture object_13)
        (texture object_14)
        (texture object_16)
        (texture object_15)
        (texture object_10)
        (texture object_8)
        (texture object_12)
        (texture object_11)
        (collect object_15 object_4)
        (collect object_13 object_3)
        (collect object_14 object_4)
        (collect object_9 object_2)
        (collect object_10 object_2)
        (collect object_12 object_3)
        (collect object_8 object_2)
        (collect object_11 object_3)
        (collect object_16 object_4)
        (spring object_11)
        (spring object_8)
        (spring object_14)
        (hand object_19)
        (hand object_21)
        (hand object_23)
        (hand object_18)
        (hand object_20)
        (hand object_22)
        (hand object_17)
        (next object_22 object_8)
        (next object_6 object_12)
        (next object_23 object_13)
        (next object_0 object_8)
        (next object_7 object_16)
        (next object_20 object_13)
        (next object_18 object_16)
        (next object_17 object_11)
        (next object_19 object_8)
        (next object_21 object_11)
        (next object_1 object_11)
        (next object_5 object_10)
    )

    (:goal
        (and (next object_21 object_16) (next object_19 object_10) (next object_23 object_14) (next object_18 object_14) (next object_20 object_10) (next object_22 object_14) (next object_17 object_14))
    )

    
    
    
)

