
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance-31)
    (:domain obfuscated_deceptive_logistics)

    (:objects
        object_0 object_1 object_10 object_11 object_12 object_13 object_14 object_2 object_3 object_4 object_5 object_6 object_7 object_8 object_9 - object
    )

    (:init
        (cats object_0)
        (stupendous object_2)
        (stupendous object_1)
        (sneeze object_4)
        (sneeze object_3)
        (texture object_9)
        (texture object_5)
        (texture object_7)
        (texture object_6)
        (texture object_10)
        (texture object_8)
        (collect object_7 object_1)
        (collect object_10 object_2)
        (collect object_6 object_1)
        (collect object_8 object_2)
        (collect object_5 object_1)
        (collect object_9 object_2)
        (spring object_8)
        (spring object_5)
        (hand object_11)
        (hand object_14)
        (hand object_13)
        (hand object_12)
        (next object_12 object_8)
        (next object_14 object_5)
        (next object_3 object_5)
        (next object_4 object_10)
        (next object_0 object_8)
        (next object_11 object_6)
        (next object_13 object_6)
    )

    (:goal
        (and (next object_11 object_10) (next object_12 object_6) (next object_13 object_10) (next object_14 object_7))
    )

    
    
    
)

