
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance-8)
    (:domain obfuscated_deceptive_logistics)

    (:objects
        object_0 object_1 object_10 object_2 object_3 object_4 object_5 object_6 object_7 object_8 object_9 - object
    )

    (:init
        (cats object_0)
        (cats object_1)
        (stupendous object_2)
        (stupendous object_3)
        (sneeze object_4)
        (sneeze object_5)
        (texture object_7)
        (texture object_8)
        (texture object_9)
        (texture object_6)
        (collect object_7 object_2)
        (collect object_6 object_2)
        (collect object_8 object_3)
        (collect object_9 object_3)
        (spring object_8)
        (spring object_6)
        (hand object_10)
        (next object_10 object_9)
        (next object_1 object_6)
        (next object_4 object_6)
        (next object_0 object_8)
        (next object_5 object_9)
    )

    (:goal
        (next object_10 object_6)
    )

    
    
    
)

