
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance-45)
    (:domain obfuscated_deceptive_logistics)

    (:objects
        object_0 object_1 object_10 object_11 object_2 object_3 object_4 object_5 object_6 object_7 object_8 object_9 - object
    )

    (:init
        (cats object_0)
        (cats object_1)
        (stupendous object_2)
        (stupendous object_4)
        (stupendous object_3)
        (sneeze object_7)
        (sneeze object_6)
        (sneeze object_5)
        (texture object_8)
        (texture object_9)
        (texture object_10)
        (collect object_9 object_3)
        (collect object_10 object_4)
        (collect object_8 object_2)
        (spring object_8)
        (spring object_9)
        (spring object_10)
        (hand object_11)
        (next object_5 object_8)
        (next object_11 object_8)
        (next object_6 object_9)
        (next object_7 object_10)
        (next object_1 object_8)
        (next object_0 object_10)
    )

    (:goal
        (next object_11 object_9)
    )

    
    
    
)

